<?php

namespace FacultyBundle\Repository;

/**
 * DivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisionRepository extends \Doctrine\ORM\EntityRepository
{


    public function findFacultyByDivison($id)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->select('d', 'faculty');
        $qb->join('d.id', 'faculty');
        $qb->where('d.id = :id');
        $qb->setParameter('id', $id);
        return $qb->getQuery()->getResult();

    }
}