<?php

namespace FacultyBundle\Repository;

/**
 * FacultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFacultyWithDivision ()
    {
        $qb = $this->createQueryBuilder('f');
        $qb->select('f', 'division');
        $qb->join('f.division', 'division');
        return $qb->getQuery()->getResult();
    }
    public function findFacultyWithDivisionById ($id)
    {
        $qb = $this->createQueryBuilder('f');
        $qb->select('f','division');
        $qb->join('f.division','division');
        $qb->where('f.id = :id');
        $qb->setParameter('id',$id);
        return $qb->getQuery()->getSingleResult();

    }

    public function findFacultyWithDivisionName ($name)
    {
        $qb = $this->createQueryBuilder('f');
        $qb->select('f');
        $qb->where('f.division= :name');
        $qb->setParameter('name', $name);
        return $qb->getQuery()->getResult();
    }

}
